### ISSUE TITLE
ipad端想同步keepassXC，把密码库和密匙文件下载到了ipad上，死活无法解开这个数据库，连进去都进去不了…

### ISSUE THREAD

**Issue by coolcat870** [kaich/FPOSite#11]
真的弄了很久…火冒三丈…密码没问题，文件密匙也没问题。因为同样的密码和文件密匙在Keepasium上就能解开，在奇密上就连进都进不去…亏我还花了钱买下了…浪费了我3个小时的时间

**Comment by kaich** [comment]
先用keeweb试试能不能解锁，macpass等软件看看能不能解锁

**Comment by coolcat870** [comment]
> 先用keeweb试试能不能解锁，macpass等软件看看能不能解锁

emmm…qq群里有群友和我一样无法在ipad上用奇密解开数据库，我新建了测试数据库和测试密匙照样无法打开（测试样本和密码和密匙文件发给qq群的群主了）…最后无奈换用了StrongBox  （StrongBox和Keepassium上能打开）  keeweb和macpass没有尝试

**Comment by kaich** [comment]
他们没有春节，春节期间他们更新了东西。
