### ISSUE TITLE
自动填充时复制密码无法顺利复制到系统剪贴板

### ISSUE THREAD

**Issue by HoldOnBro** [kaich/FPOSite#19]
显示为：可能由于系统限制......

iPhone11, iOS 14.7.1

**Comment by HoldOnBro** [comment]
目前就发现这三个小问题，其它方面已经很完美了。感谢作者的付出。

**Comment by kaich** [comment]
系统限制了啊，不让复制，所以弹窗提示

**Comment by HoldOnBro** [comment]
strongbox和1password都能成功复制，应该有办法bypass

**Comment by HoldOnBro** [comment]
> 系统限制了啊，不让复制，所以弹窗提示

strongbox和1password都能成功复制，应该有办法bypass

**Comment by kaich** [comment]
到时候我看看

**Comment by kaich** [comment]
不对啊，strongbox压根不行啊。

**Comment by HoldOnBro** [comment]
> 不对啊，strongbox压根不行啊。

可以，我在tf里，测试过了

**Comment by HoldOnBro** [comment]
> 不对啊，strongbox压根不行啊。

复制的是otp，strongbox不提供自动复制密码选项，不过道理是一样的，fantasypass自动复制otp也提示系统限制。

**Comment by kaich** [comment]
键盘上方直接填充是不可以的，出现了软件的页面那种填充是可以的。我试过了，目前奇密也是这样

**Comment by HoldOnBro** [comment]
> 键盘上方直接填充是不可以的，出现了软件的页面那种填充是可以的。我试过了，目前奇密也是这样

我的测试场景是网页端的 steam，strongbox 和 1password 在自动填充了账号密码后可以自动复制 otp 到剪贴板

**Comment by kaich** [comment]
用strongbox， 键盘上方点要填充的密码 -》 弹出登录的页面 =》 输入密码成功复制了TOTP =》重新填充 =》 此时不会弹出登录窗口 =》 复制TOTP失败
